batch_size = 128
shuffle    = true 
num_workers= 4
pin_memory = true

[optimizer]
lr = 0.1
momentum = 0.9

[scheduler]
step_size = 15
gamma = 0.1


[training]
num_epochs = 15


[data]
dir_path = "../../data"

[model]
dropout_rate = 0.01
bias = false